#ifndef __CONSTANTS_H__
#define __CONSTANTS_H__

#define SUCCESS 1
#define FAILURE 0

#define DATA_FORMAT_DVB 1
#define DATA_FORMAT_FREESAT 2
#define DATA_FORMAT_SKYBOX 3
#define DATA_FORMAT_MHW_1 4 
#define DATA_FORMAT_MHW_2 5
#define DATA_FORMAT_FILE 6
#define DATA_FORMAT_SCRIPT 9

#define MAX_FILTERS 24

#endif
